version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Building NextJS app
      - npm run build
artifacts:
  files:
    - 'node_modules/**/*'
    - '.next/**/*'
    - 'package.json'
    - 'package-lock.json'
    - '.ebextensions/*'


  
